#TODO put under single namespace
mu: 0.0
sigma: 0.3
sigma_filter: 3.5
length: 5.5 # length of the terrain in meters, m
width: 4.5 # width of terrain in meters, m
resolution: 0.025 # size of single terrain grid cell in meters per cell,  m/cell
v_length: 0.05 # vehicle length in meters, m
v_width: 0.025 # vehicle width in meters, m


